version: '3'

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    #environment:
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: example

  grpc-java-service:
    image: learningtour786/grpc-java-course
    ports:
      - "50051:50051"
    restart: always
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3